package it.italiaonline.rnd

import groovy.util.logging.Slf4j

/**
 * This Groovy source file was auto generated by 'gigawatt'
 * @author gsus
 * @date 28-11-2016 10.53
 */
@Slf4j
class Library {
	/**
	 * This method returns always true.
	 */
	Boolean someLibraryMethod() {
		true
	}
}
